FROM php:7.4-fpm

RUN apt update && apt install -y curl nano
RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

WORKDIR /var/www
COPY --chown=www:www . /var/www

USER www

RUN php artisan config:clear
RUN php artisan config:cache
#RUN php artisan migrate

EXPOSE 9000
CMD ["php-fpm"]